### ISSUE TITLE
What do you think about improve the library name?

### ISSUE THREAD

**Issue by pedroSoaresll** [pmqueiroz/mask-wizard#3]
### Problem 
This library name does not say what exactly it does. For example, Mask Wizard, when I think in some module about a mask I think something like format phone number, document, or other mask

But apparently, this library is about the time, right?
What about some name like Mask Time

@pmqueiroz

**Comment by pmqueiroz** [comment]
> But apparently, this library is about the time, right?

Actually no :c

I'm starting with time mask but my wish is mask many kinds of formats, like you mentioned "phone number, document, or other masks" that's why i choose this name :)
